name: Swift Coverage Test
description: Extract test coverage information for a swift package.

inputs:
   ssh-private-key:
        description: The private ssh key.
        type: string
        required: true

runs:
    using: 'composite'

    steps:
      - uses: gilmourspace/install-swift@main

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }} 

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
        run: swift test --enable-code-coverage
        shell: bash

      - name: Coverage Test
        uses: mattpolzin/swift-codecov-action@0.7.3
        id: cov
        with:
          MINIMUM_COVERAGE: 80

      - name: Post Positive Result
        if: ${{ success() }}
        run: |
          echo "::warning file=Package.swift,line=1,col=1::The current code coverage percentage is passing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
        shell: bash

      - name: Post Negative Result
        if: ${{ failure() }}
        run: |
          echo "::error file=Package.swift,line=1,col=1::The current code coverage percentage is failing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
        shell: bash
